name: Minecraft Bot 24/7
on:
  push:
    branches: [ develop, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Configure
        run: |
          echo '{"google": "${{ secrets.GEMINI_API_KEY }}"}' > keys.json
          echo "export default {
            host: 'gptoi.aternos.me',
            port: 50962,
            auth: 'offline',
            profiles: ['./profiles/gemini.json'],
            load_memory: false,
            init_message: 'Hello! I am Gemini.',
            only_chat_with: []
          }" > settings.js

      - name: Start Bot
        run: node main.js
        env:
          MODEL_PROVIDER: 'google'
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
